# get themes from:
# https://github.com/ckolos/alacritty-theme-toml
# import = ["/Users/jr/.config/alacritty/nord.toml"]
import = ["/Users/jr/.config/alacritty/solarized_light.toml"]
live_config_reload = true

[cursor]
blink_timeout = 0
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = false
size = 17

[font.normal]
family = "MonoLisa JR"
style = "Light"

[font.italic]
family = "MonoLisa JR"
style = "Light Italic"

[font.bold]
family = "MonoLisa JR"
style = "Bold"

[font.bold_italic]
family = "MonoLisa JR"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 2

[font.offset]
x = 0
y = 0

[hints]
alphabet = "sateribhcumony"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control | Shift"

[hints.enabled.mouse]
enabled = false
mods = "None"

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"
opacity = 1#0.95
blur = true

[window.dimensions]
columns = 264
lines = 64

[window.padding]
x = 15
y = 15
