[colors.primary]
background = '#fdf6e3' # base3
foreground = '#657b83' # base00

[colors.cursor]
text = '#fdf6e3'   # base3
cursor = '#657b83' # base00

[colors.normal]
black = '#073642'   # base02
red = '#dc322f'     # red
green = '#859900'   # green
yellow = '#b58900'  # yellow
blue = '#268bd2'    # blue
magenta = '#d33682' # magenta
cyan = '#2aa198'    # cyan
white = '#eee8d5'   # base2

[colors.hints.end]
background = "#9ccfd8"
foreground = "#232136"

[colors.hints.start]
background = "#e0def4"
foreground = "#232136"
