[[ language ]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = ["html"]
roots = []
language-server = { command = "html-languageserver", args = ["--stdio"] }
auto-format = true
config = { "provideFormatter" = true }
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "html"
source = { git = "https://github.com/tree-sitter/tree-sitter-html", rev = "d93af487cc75120c89257195e6be46c999c6ba18" }

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]
roots = [".git"]
comment-token = "#"
language-server = { command = "pylsp" }
auto-format = true
# config = { "formatCommand" = "black" }
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }

[language.config]
formatCommand = "black"

[language.config.pylsp.plugins.black]
enabled = true

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "de221eccf9a221f5b85474a553474a69b4b5784d" }