os:
  editCommand: "hx"

# keybinding:
#   universal:
#     return: '<c-\>'

gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
git:
  paging:
    colorArg: never
    pager: delta --dark --plus-style 'black green' --minus-style 'black red' --paging=never
  disableForcePushing: true

customCommands:
  - key: K
    command: git difftool
    context: global
    subprocess: true

promptToReturnFromSubprocess: false
