theme = "solarized_light_custom"

[editor]
cursorline = true
cursorcolumn = true
line-number = "relative"
color-modes = true
shell = ["nu", "-c"]
bufferline = "always"
auto-pairs = true
mouse = true
completion-trigger-len = 1
# rulers = [80]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.whitespace.characters]
newline = "↵"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "file-name"]
right = ["version-control", "spacer", "diagnostics", "selections", "position", "total-line-numbers", "file-encoding"]
mode.normal = "nor"
mode.insert = "ins"
mode.select = "sel"

[keys.normal]
"ret" = ["open_below", "normal_mode"]
"X" = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
c = ":buffer-close"
C = ":buffer-close-others"

[keys.normal.backspace]
c = ":config-open"
s = ":config-reload"
r = ":reload"
R = ":reload-all"
l = ":lsp-restart"
"w" = ":write"
"W" = ":write-all"
"q" = ":quit"
"Q" = ":write-quit"

[keys.select]
"X" = ["extend_line_up", "extend_to_line_bounds"]

