theme = "rose_pine_moon_custom"

[editor]
cursorline = true
cursorcolumn = true
line-number = "relative"
color-modes = true
shell = ["nu", "-c"]
bufferline = "always"
rulers = [100]

[editor.cursor-shape]
normal = "block"
insert = "bar"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.whitespace.characters]
newline = "⤶"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[keys.normal]
"ret" = ["open_below", "normal_mode"]

[keys.normal.space]
c = ":buffer-close"
C = ":buffer-close-others"
# W = ":write"
# Q = ":quit"
# i = ":insert-output"

[keys.normal.backspace]
c = ":config-open"
s = ":config-reload"

# [keys.insert]
# j = { b = "normal_mode" }