theme = "catppuccin_frappe_custom"

[editor]
cursorline = true
cursorcolumn = true
line-number = "relative"
color-modes = true
shell = ["nu", "-c"]
bufferline = "always"
auto-pairs = true
mouse = false
completion-trigger-len = 0
# rulers = [80]

[editor.cursor-shape]
normal = "block"
insert = "bar"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.whitespace.characters]
newline = "↵"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "file-name"]
right = ["version-control", "spacer", "diagnostics", "selections", "position", "total-line-numbers", "file-encoding"]
mode.normal = "nor"
mode.insert = "ins"
mode.select = "sel"

[keys.normal]
"ret" = ["open_below", "normal_mode"]
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme rose_pine_moon_custom"]

[keys.normal.space]
c = ":buffer-close"
C = ":buffer-close-others"
i = ":toggle lsp.display-inlay-hints"
"minus" = ":write"

[keys.normal.backspace]
c = ":config-open"
s = ":config-reload"
r = ":reload"
R = ":reload-all"
l = ":lsp-restart"

