# python

[language-server.pylsp]
command = "pylsp"
[language-server.pylsp.config]
provideFormatter = true

[language-server.pylsp.config.plugins.pycodestyle]
enabled = false

[language-server.pylsp.config.plugins.flake8]
enabled = true
maxLineLength = 79

[language-server.pylsp.config.plugins.pyflakes]
enabled = false

[language-server.black]
command = "black"
args = ["--quiet", "--line-length=79"]

[language-server.isort]
command = "isort"
args = []

[[grammar]]
name = "html"
source = { git = "https://github.com/tree-sitter/tree-sitter-html", rev = "29f53d8f4f2335e61bf6418ab8958dac3282077a" }

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct", "rpy", "cpy", "ipy", "pyt", "SConscript"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = [{ name = "pylsp", except-features = ["format"]},]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "sh", args = ["-c", "isort - | black --quiet --line-length=79 -"]}

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "de221eccf9a221f5b85474a553474a69b4b5784d" }

# html

[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = ["html", "htm", "shtml", "xhtml", "xht", "jsp", "asp", "aspx", "jshtm", "volt", "rhtml"]
roots = []
language-servers = [ "vscode-html-language-server" ]
auto-format = false
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "c"
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }
auto-format = true
